services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:5000"
      - "${PYTHON_PORT}:5001"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - profile-matcher-mongodb-data:/data/db
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
volumes:
  profile-matcher-mongodb-data: